version: "2.1"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
    ports:
      - 8080:8080
    network_mode: "host"
    restart: unless-stopped

